#====================Spring Boot和Mybatis整合 数据库连接参数=======================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 186000
    url: jdbc:mysql://47.95.198.1:3306/poem?useUnicode=true&characterEncoding=utf-8
mybatis:
  # mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.sclience.entity
server:
  port: 8088

